### ISSUE TITLE
Add Classes

### ISSUE THREAD

**Issue by Lyxal** [Vyxal/Vyxal#250]

**Comment by ysthakur** [comment]
Once we finish basic classes, I have the following lower-priority feature requests:
- Shorter constructors, either like Scala or like C++ (I lean heavily toward the former)
- Extending/opening classes like Ruby using the same class syntax, instead of saying `Foo.bar = ...` for monkey-patching
- Letting classes define identities for addition/multiplication, overload builtins themselves, etc.

**Comment by Lyxal** [comment]
I'll come up with some syntax examples for y'all and see what y'all like best

**Comment by ysthakur** [comment]
@Lyxal Do you want to make a Discussion instead, then? It'll be easier to vote on the syntaxes and stuff.
