### ISSUE TITLE
Lazy eval breaks stuff  sometimes 

### ISSUE THREAD

**Issue by chunkybanana** [Vyxal/Vyxal#470]
[This should return `[1,1,1,1,1],[2,2,2,2,2]`](https://vyxal.pythonanywhere.com/#WyIiLCIiLCIyKCBuIMKjIDUgxpsgwqUgOyApIFwiIiwiIiwiIl0=)

The issue is that it's lazily evaluating the expression after the register has been reset, causing problems

The only way I can think of to  fix this is to save a copy of the context variable when a lazylist is initialized or modified, and I'm not even sure if that's possible...

**Comment by Bubbler-4** [comment]
That's a common problem with lazy evaluation mixed with side effects. It is not recommended to mix the two, since the result is pretty much unpredictable. It's also one of the reasons Haskell is so hard to debug, even with printing debugging via `Debug.Trace`.

In this case, it looks like each loop iteration is pushing 5 copies of a lazy reference to the register. That's... uh... a pretty sus design.

Possible ideas:

* Add a built-in that, given a value that possibly contains a lazy reference, fully evaluates it. (This is probably the best choice; when you want to control the order of evaluation, you can put it as needed. e.g. if `<Force>` is the built-in, `￥<Force>` will always give the value of the register at the time of request.)
* Add a flag that disables lazy evaluation.

Something for documentation:

* "Lazy doesn't mix well with side effects (such as writing and reading the register). If you see surprising results, consider applying the Force built-in on the data."

**Comment by Lyxal** [comment]
This is basically what causes the vectorised printing bug.

**Comment by Lyxal** [comment]
#336

**Comment by Lyxal** [comment]
https://chat.stackexchange.com/transcript/106764?m=59942945#59942945

**Comment by cgccuser** [comment]
I agree with @Bubbler-4 about adding a "Force evaluation of lazylist" builtin. We could also add a "foreach" builtin that strictly iterates through a lazylist as an alternative to map. But it isn't lazy evaluation itself that's the problem, that's kinda by design.
