### ISSUE TITLE
V flag never got implemented

### ISSUE THREAD

**Issue by chunkybanana** [Vyxal/Vyxal#629]
The V flag for single-character variables never got implemented

**Comment by razetime** [comment]
what exactly should this flag do? is it detailed anywhere?

**Comment by AMiller42** [comment]
> what exactly should this flag do? is it detailed anywhere?

The flag causes all variable names to be one character long, meaning that characters that would normally be interpreted as part of the variable name can instead be used as normal commands. This was implemented in the old interpreter, so you can see how it works on the lyxal.pa site: [Try it Online!](https://lyxal.pythonanywhere.com?flags=Vc&code=3%E2%86%92x%E2%86%90xd&inputs=&header=&footer=)

The way that it is implemented there is that the character immediately following one of the `→← ` commands is used for the variable name, regardless of if that character would normally be valid for a variable name. It is converted to its UTF-8 codepoint, and that number is used for the variable name, e.g. `→x` will store the top of the stack in the variable `VAR_120`. We don’t necessarily need to implement it exactly like that, but it would still be good to implement the flag in some way.

**Comment by Tams-Tams** [comment]
@AMiller42 Why was the variable's name was its UTF-8 codepoint? Are there any reasons to use the UTF-8 codepoint now, if it gets implemented?

**Comment by AMiller42** [comment]
@Tams-Tams My guess is that it was implemented that way to increase the number of variables available, since using characters like `∑` or `∆` in variable names wouldn’t work. We wouldn’t necessarily need to implement it that way, but that’s how it was implemented originally. The only real drawback i can see for doing it that way is that it prevents us from using global variables or the ghost variable.
