### ISSUE TITLE
`ȯ` doesn't work with negatives

### ISSUE THREAD

**Issue by chunkybanana** [Vyxal/Vyxal#710]
# [Vyxal](https://github.com/Vyxal/Vyxal), 1 byte
```
ȯ
```
[Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCLIryIsIiIsIi0yXG5bMSwgMiwgMywgNF0iXQ==)

**Comment by Tams-Tams** [comment]
I looked and tested a bit of the code, and I *think* it is a LazyList problem. When the function `index` gets called, it turns the list into an `iterable`, and there, everything's okay. But when the `iterable` gets sliced (with `slice([-2, None, None])`, it returns `⟨  ⟩`. `temp` is a LazyList, and my guess is the bug is in the function `LazyList.__getitem__`. But I could be completely wrong.
