### ISSUE TITLE
Add Integer support for flags `C` and `L`

### ISSUE THREAD

**Issue by Tams-Tams** [Vyxal/Vyxal#721]
[Try C online](https://vyxal.pythonanywhere.com/#WyJDIiwiIiwi4p+oMXwyfDPin6kiLCIiLCIiXQ==) | [Try L online](https://vyxal.pythonanywhere.com/#WyJMIiwiIiwi4p+oMXwyfDPin6kiLCIiLCIiXQ==)

**Comment by AMiller42** [comment]
It looks like this isn't actually a problem with the flags, it's a problem with the `øĊ` and `§` commands, which error on integers. They each error for their own reasons, but they can both be fixed by vectorising `vy_str` over `lhs`, which makes the commands work as they should for numbers, without changing the behavior for strings. I'll write up a PR real quick to fix it.
