### ISSUE TITLE
`Ẋ` outputs in a... strange order

### ISSUE THREAD

**Issue by Steffan153** [Vyxal/Vyxal#985]
[Try it Online!](https://vyxal.pythonanywhere.com/#WyJQIiwiIiwi4bqKIiwiIiwiWzEsIDIsIDNdXG5bMSwgMiwgM10iXQ==)

Compare to [Old vyxal](https://lyxal.pythonanywhere.com?flags=&code=%E1%BA%8A&inputs=%5B1%2C%202%2C%203%5D%0A%5B1%2C%202%2C%203%5D&header=&footer=), [Jelly](https://tio.run/##y0rNyan8/7/g////0YY6CkY6CsaxCBYA "Jelly – Try It Online"), and [05AB1E](https://tio.run/##yy9OTMpM/f//8KL//6MNdRSMdBSMY7ngLAA "05AB1E – Try It Online").

**Comment by chunkybanana** [comment]
It's because of how cartesian product must be taken over infinite lists. It's equivalent to, say, enumerating all possible fractions:

![a](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.HLLeqp51rKXoQJUfzOphEwHaFO%26pid%3DApi&f=1)

And we can't really make it output in a different way until we fix #670.

**Comment by Steffan153** [comment]
Can we then add a digraph that does not support infinite lists?

**Comment by cgccuser** [comment]
@Steffan153 That sounds fine to me

**Comment by Steffan153** [comment]
> @Steffan153 That sounds fine to me, do you want to implement it or should I?

Actually, `"Π` works fine, so it's not needed.
